/* Minimal wolfSSL for iOS 5.1.1 armv7 — TLS 1.2 only */
#define WOLFSSL_TLS12
#define NO_OLD_TLS
#define HAVE_TLS_EXTENSIONS
#define HAVE_SNI
#define HAVE_AESGCM
#define WOLFSSL_STATIC_RSA
#define HAVE_ECC
#define ECC_SHAMIR
#define TFM_ECC256
#define WOLFSSL_SHA384
#define WOLFSSL_SHA512
#define NO_FILESYSTEM
#define NO_WRITEV
#define SINGLE_THREADED
#define NO_DEV_RANDOM
#define CUSTOM_RAND_GENERATE_BLOCK
#define WOLFSSL_SMALL_STACK
#define NO_DSA
#define NO_PSK
#define NO_MD4
#define NO_HC128
#define NO_RABBIT
#define NO_DH
#define WC_NO_ASYNC_THREADING
#define HAVE_HASHDRBG
#define WC_RSA_BLINDING
